services:
  - type: web
    name: movie-recommender-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_railway_simple:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 